# Generated by Django 4.2.11 on 2024-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='send_date',
            field=models.DateField(help_text='The proposal send date', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='valid_date',
            field=models.DateField(help_text='The proposal valid date', null=True),
        ),
    ]
