# Generated by Django 4.2.11 on 2024-05-18 21:12

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_proposal_customer_email_proposal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
