# Generated by Django 4.2.11 on 2024-05-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customers_status'),
        ('jobschedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('start_hour', models.DateTimeField(blank=True, null=True)),
                ('end_hour', models.DateTimeField(blank=True, null=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.crew')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobschedules.jobs')),
            ],
        ),
    ]
