# Generated by Django 4.2.11 on 2024-05-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobschedules', '0003_assignedjob_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedjob',
            name='blow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedjob',
            name='edge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedjob',
            name='mow',
            field=models.BooleanField(default=False),
        ),
    ]
