# Generated by Django 4.2.11 on 2024-04-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='crew_members',
        ),
        migrations.AddField(
            model_name='crewmember',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.crew'),
        ),
    ]
