# Generated by Django 4.2.11 on 2024-04-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_crew_crew_members_crewmember_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='users.crew')),
            ],
        ),
    ]
