# Generated by Django 4.2.11 on 2024-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
