# Generated by Django 4.2.20 on 2025-04-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customers_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('-id',), 'verbose_name': 'Customer Record', 'verbose_name_plural': 'Customers'},
        ),
    ]
