# Generated by Django 4.2.20 on 2025-04-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('-id',), 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
